/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/FbResourcesLabour copy.vue')['default']
    FbBadge: typeof import('./src/components/FbBadge.vue')['default']
    FbBuildings: typeof import('./src/components/FbBuildings.vue')['default']
    FbBuildingsBox: typeof import('./src/components/FbBuildingsBox.vue')['default']
    FbBuildingsBoxInner: typeof import('./src/components/FbBuildingsBoxInner.vue')['default']
    FbButton: typeof import('./src/components/FbButton.vue')['default']
    FbColoredIcon: typeof import('./src/components/FbColoredIcon.vue')['default']
    FbIcon: typeof import('./src/components/FbIcon.vue')['default']
    FbJobs: typeof import('./src/components/FbJobs.vue')['default']
    FbJobsBox: typeof import('./src/components/FbJobsBox.vue')['default']
    FbLaws: typeof import('./src/components/FbLaws.vue')['default']
    FbLawsItem: typeof import('./src/components/FbLawsItem.vue')['default']
    FbPopoverDetails: typeof import('./src/components/FbPopoverDetails.vue')['default']
    FbResourceIcon: typeof import('./src/components/FbResourceIcon.vue')['default']
    FbResources: typeof import('./src/components/FbResources.vue')['default']
    FbResourcesBuilding: typeof import('./src/components/FbResourcesBuilding.vue')['default']
    FbResourcesHappiness: typeof import('./src/components/FbResourcesHappiness.vue')['default']
    FbResourcesItem: typeof import('./src/components/FbResourcesItem.vue')['default']
    FbResourcesLabour: typeof import('./src/components/FbResourcesLabour.vue')['default']
    FbResourcesScience: typeof import('./src/components/FbResourcesScience.vue')['default']
    FbSymbol: typeof import('./src/components/FbSymbol.vue')['default']
    FbTabs: typeof import('./src/components/FbTabs.vue')['default']
    FbTownHall: typeof import('./src/components/FbTownHall.vue')['default']
    FbTownHallImage: typeof import('./src/components/FbTownHallImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
